package main;

import java.awt.Color;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import view.FormBarangRusak;
import view.FormDashboard;
import view.FormSupplier;
import view.FormInventori;
import view.FormKelolaKaryawan;
import view.FormLaporanPenjualan;
import view.FormPembelian;
import view.FormPenjualan;
import java.sql.Connection;
import javax.swing.JLabel;
import javax.swing.JPanel;
import view.FormPembelian1;


public class MenuUtama extends javax.swing.JFrame {
    
    private String role;
     private Connection conn;

    
    public MenuUtama() {
    initComponents();
    this.role = "admin";
    aturAksesMenu();

    setLocationRelativeTo(null);
    setTitle("ATK Fatimah");
    setIconImage(new ImageIcon(getClass().getResource("/gambar/logoatk.png")).getImage());

    try {
        conn = Koneksi.getConnection(); // ✅ dibungkus try-catch
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal koneksi ke database: " + e.getMessage());
    }
}

    public MenuUtama(String role) {
    initComponents();
    this.role = role;
    aturAksesMenu();

    setLocationRelativeTo(null);
    setTitle("ATK Fatimah");
    setIconImage(new ImageIcon(getClass().getResource("/gambar/logoatk.png")).getImage());

    try {
        conn = Koneksi.getConnection();
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal koneksi ke database: " + e.getMessage());
    }
}

    
    
    private void nonaktifkanAkses(JLabel label, JPanel panel) {
    // Hapus semua mouse listener dari label (karena hanya label yang interaktif)
    for (MouseListener ml : label.getMouseListeners()) {
        label.removeMouseListener(ml);
    }

    
}
    
    

    private void aturAksesMenu() {
    if (role.equalsIgnoreCase("kasir")) {
        // Tampilkan semua menu
        btn_pembelian.setVisible(true);
        btn_inventaris.setVisible(true);
        btn_barang_rusak.setVisible(true);
        btn_supplier.setVisible(true);
        btn_laporan.setVisible(true);
        btn_karyawan.setVisible(true);

        // Nonaktifkan akses menu tertentu untuk kasir
        nonaktifkanAkses(pembelian, btn_pembelian);
        nonaktifkanAkses(inventaris, btn_inventaris);
        nonaktifkanAkses(barang_rusak, btn_barang_rusak);
        nonaktifkanAkses(supplier, btn_supplier);
        nonaktifkanAkses(laporan_penjualan, btn_laporan);
        nonaktifkanAkses(karyawan, btn_karyawan);
    }
}


    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new main.gradasiwarna();
        pn_kiri = new main.gradasiwarna();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JPanel();
        logo_dashboard = new javax.swing.JLabel();
        Dashboard = new javax.swing.JLabel();
        btn_penjualan = new javax.swing.JPanel();
        logo_penjualan = new javax.swing.JLabel();
        penjualan = new javax.swing.JLabel();
        btn_pembelian = new javax.swing.JPanel();
        logo_pembelian = new javax.swing.JLabel();
        pembelian = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_inventaris = new javax.swing.JPanel();
        logo_inventaris = new javax.swing.JLabel();
        inventaris = new javax.swing.JLabel();
        btn_barang_rusak = new javax.swing.JPanel();
        logo_barang_rusak = new javax.swing.JLabel();
        barang_rusak = new javax.swing.JLabel();
        btn_supplier = new javax.swing.JPanel();
        logo_supplier = new javax.swing.JLabel();
        supplier = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_laporan = new javax.swing.JPanel();
        logo_laporan = new javax.swing.JLabel();
        laporan_penjualan = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btn_karyawan = new javax.swing.JPanel();
        logo_karyawan = new javax.swing.JLabel();
        karyawan = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btn_logut = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        dashboard.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        dashboard.setForeground(new java.awt.Color(255, 255, 255));
        dashboard.setText("Dashboard");
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pn_kanan.setLayout(new java.awt.BorderLayout());

        pn_dasar.setBackground(new java.awt.Color(204, 204, 255));

        pn_utama.setBackground(new java.awt.Color(0, 0, 255));
        pn_utama.setPreferredSize(new java.awt.Dimension(755, 509));
        pn_utama.setLayout(new java.awt.BorderLayout());

        pn_kiri.setBackground(new java.awt.Color(0, 0, 255));
        pn_kiri.setPreferredSize(new java.awt.Dimension(270, 768));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/logo (1).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Menu");

        btn_dashboard.setBackground(new java.awt.Color(17, 107, 175));

        logo_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/dash (1).png"))); // NOI18N
        logo_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logo_dashboardMouseClicked(evt);
            }
        });

        Dashboard.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Dashboard.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard.setText("Dashboard");
        Dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_dashboardLayout = new javax.swing.GroupLayout(btn_dashboard);
        btn_dashboard.setLayout(btn_dashboardLayout);
        btn_dashboardLayout.setHorizontalGroup(
            btn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_dashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_dashboardLayout.setVerticalGroup(
            btn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_dashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo_dashboard, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        btn_penjualan.setBackground(new java.awt.Color(0, 120, 215));
        btn_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_penjualanMouseExited(evt);
            }
        });

        logo_penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kasir (1).png"))); // NOI18N

        penjualan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        penjualan.setForeground(new java.awt.Color(255, 255, 255));
        penjualan.setText("Penjualan");
        penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penjualanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                penjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                penjualanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_penjualanLayout = new javax.swing.GroupLayout(btn_penjualan);
        btn_penjualan.setLayout(btn_penjualanLayout);
        btn_penjualanLayout.setHorizontalGroup(
            btn_penjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_penjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_penjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_penjualanLayout.setVerticalGroup(
            btn_penjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_penjualanLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(btn_penjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo_penjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(penjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btn_pembelian.setBackground(new java.awt.Color(17, 107, 175));
        btn_pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pembelianMouseExited(evt);
            }
        });

        logo_pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kasir (1).png"))); // NOI18N

        pembelian.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pembelian.setForeground(new java.awt.Color(255, 255, 255));
        pembelian.setText("Pembelian");
        pembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pembelianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pembelianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pembelianMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_pembelianLayout = new javax.swing.GroupLayout(btn_pembelian);
        btn_pembelian.setLayout(btn_pembelianLayout);
        btn_pembelianLayout.setHorizontalGroup(
            btn_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_pembelianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_pembelian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_pembelianLayout.setVerticalGroup(
            btn_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_pembelianLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(btn_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo_pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/line.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Barang");

        btn_inventaris.setBackground(new java.awt.Color(17, 107, 175));
        btn_inventaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_inventarisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_inventarisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_inventarisMouseExited(evt);
            }
        });

        logo_inventaris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/inventaris.png"))); // NOI18N

        inventaris.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        inventaris.setForeground(new java.awt.Color(255, 255, 255));
        inventaris.setText("Inventaris");
        inventaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventarisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventarisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventarisMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_inventarisLayout = new javax.swing.GroupLayout(btn_inventaris);
        btn_inventaris.setLayout(btn_inventarisLayout);
        btn_inventarisLayout.setHorizontalGroup(
            btn_inventarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_inventarisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_inventaris, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventaris, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_inventarisLayout.setVerticalGroup(
            btn_inventarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_inventarisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_inventarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logo_inventaris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventaris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btn_barang_rusak.setBackground(new java.awt.Color(17, 107, 175));
        btn_barang_rusak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_barang_rusakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_barang_rusakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_barang_rusakMouseExited(evt);
            }
        });

        logo_barang_rusak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/inventaris.png"))); // NOI18N

        barang_rusak.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        barang_rusak.setForeground(new java.awt.Color(255, 255, 255));
        barang_rusak.setText("Barang Rusak");
        barang_rusak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barang_rusakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barang_rusakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barang_rusakMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_barang_rusakLayout = new javax.swing.GroupLayout(btn_barang_rusak);
        btn_barang_rusak.setLayout(btn_barang_rusakLayout);
        btn_barang_rusakLayout.setHorizontalGroup(
            btn_barang_rusakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_barang_rusakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_barang_rusak, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barang_rusak, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_barang_rusakLayout.setVerticalGroup(
            btn_barang_rusakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_barang_rusakLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_barang_rusakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logo_barang_rusak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barang_rusak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btn_supplier.setBackground(new java.awt.Color(17, 107, 175));
        btn_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_supplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_supplierMouseExited(evt);
            }
        });

        logo_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/inventaris.png"))); // NOI18N

        supplier.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        supplier.setForeground(new java.awt.Color(255, 255, 255));
        supplier.setText("Supplier");
        supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_supplierLayout = new javax.swing.GroupLayout(btn_supplier);
        btn_supplier.setLayout(btn_supplierLayout);
        btn_supplierLayout.setHorizontalGroup(
            btn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_supplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplier, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_supplierLayout.setVerticalGroup(
            btn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_supplierLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_supplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(logo_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/line.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/line.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Laporan");

        btn_laporan.setBackground(new java.awt.Color(0, 153, 221));
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_laporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_laporanMouseExited(evt);
            }
        });

        logo_laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/laporan_penjualan.png"))); // NOI18N

        laporan_penjualan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        laporan_penjualan.setForeground(new java.awt.Color(255, 255, 255));
        laporan_penjualan.setText("Laporan Penjualan");
        laporan_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporan_penjualanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                laporan_penjualanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                laporan_penjualanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_laporanLayout = new javax.swing.GroupLayout(btn_laporan);
        btn_laporan.setLayout(btn_laporanLayout);
        btn_laporanLayout.setHorizontalGroup(
            btn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_laporanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_laporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporan_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_laporanLayout.setVerticalGroup(
            btn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_laporanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_laporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo_laporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laporan_penjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Karyawan");

        btn_karyawan.setBackground(new java.awt.Color(51, 181, 255));
        btn_karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_karyawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_karyawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_karyawanMouseExited(evt);
            }
        });

        logo_karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/klola_karya.png"))); // NOI18N

        karyawan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        karyawan.setForeground(new java.awt.Color(255, 255, 255));
        karyawan.setText("Kelola Karyawan");
        karyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                karyawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                karyawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                karyawanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_karyawanLayout = new javax.swing.GroupLayout(btn_karyawan);
        btn_karyawan.setLayout(btn_karyawanLayout);
        btn_karyawanLayout.setHorizontalGroup(
            btn_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_karyawanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo_karyawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_karyawanLayout.setVerticalGroup(
            btn_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_karyawanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_karyawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo_karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/line.png"))); // NOI18N

        btn_logut.setBackground(new java.awt.Color(51, 181, 255));
        btn_logut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logutMouseExited(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tambah_karya.png"))); // NOI18N

        logout.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_logutLayout = new javax.swing.GroupLayout(btn_logut);
        btn_logut.setLayout(btn_logutLayout);
        btn_logutLayout.setHorizontalGroup(
            btn_logutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_logutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_logutLayout.setVerticalGroup(
            btn_logutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_logutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btn_logutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/line.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 204));
        jLabel27.setText("Transaksi");

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_kiriLayout.createSequentialGroup()
                                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9))))
                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pn_kiriLayout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btn_inventaris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_karyawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_barang_rusak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(btn_logut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(pn_kiriLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel1)
                                                .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_penjualan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_pembelian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(11, 11, 11)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_kiriLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btn_inventaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_barang_rusak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_logut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addComponent(pn_kiri, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_kiri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_karyawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_karyawanMouseExited

    private void btn_karyawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_karyawanMouseEntered

    private void btn_karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_karyawanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_karyawanMouseClicked

    private void karyawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanMouseExited
        btn_karyawan.setBackground(new Color(51, 181, 255));
    }//GEN-LAST:event_karyawanMouseExited

    private void karyawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanMouseEntered
        btn_karyawan.setBackground(new Color(0,0,205));
    }//GEN-LAST:event_karyawanMouseEntered

    private void karyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_karyawanMouseClicked
        btn_karyawan.setBackground(new Color(0,0,205));
        
        pn_utama.removeAll();
        pn_utama.add(new FormKelolaKaryawan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_karyawanMouseClicked

    private void btn_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseExited
        
    }//GEN-LAST:event_btn_laporanMouseExited

    private void btn_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseEntered
        
    }//GEN-LAST:event_btn_laporanMouseEntered

    private void btn_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseClicked
        
    }//GEN-LAST:event_btn_laporanMouseClicked

    private void laporan_penjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporan_penjualanMouseExited
        btn_laporan.setBackground(new Color(0, 153, 221));
    }//GEN-LAST:event_laporan_penjualanMouseExited

    private void laporan_penjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporan_penjualanMouseEntered
        btn_laporan.setBackground(new Color(0,0,205));
    }//GEN-LAST:event_laporan_penjualanMouseEntered

    private void laporan_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporan_penjualanMouseClicked
        btn_laporan.setBackground(new Color(0,0,205));
        
        pn_utama.removeAll();
        pn_utama.add(new FormLaporanPenjualan());
        pn_utama.repaint();
        pn_utama.revalidate();

    }//GEN-LAST:event_laporan_penjualanMouseClicked

    private void btn_inventarisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inventarisMouseExited
        
    }//GEN-LAST:event_btn_inventarisMouseExited

    private void btn_inventarisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inventarisMouseEntered
        
    }//GEN-LAST:event_btn_inventarisMouseEntered

    private void btn_inventarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inventarisMouseClicked


    }//GEN-LAST:event_btn_inventarisMouseClicked

    private void inventarisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarisMouseExited
        btn_inventaris.setBackground(new Color(17,107,175));
    }//GEN-LAST:event_inventarisMouseExited

    private void inventarisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarisMouseEntered
        btn_inventaris.setBackground(new Color(0,0,205));
    }//GEN-LAST:event_inventarisMouseEntered

    private void inventarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventarisMouseClicked
        btn_inventaris.setBackground(new Color(0,0,205));

        pn_utama.removeAll();
        pn_utama.add(new FormInventori());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_inventarisMouseClicked

    private void btn_penjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseExited
        btn_penjualan.setBackground(new Color(17,107,175));
    }//GEN-LAST:event_btn_penjualanMouseExited

    private void btn_penjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseEntered
        btn_penjualan.setBackground(new Color(0,0,205));
    }//GEN-LAST:event_btn_penjualanMouseEntered

    private void btn_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_penjualanMouseClicked
        btn_penjualan.setBackground(new Color(0,0,205));

    }//GEN-LAST:event_btn_penjualanMouseClicked

    private void penjualanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penjualanMouseExited
        btn_penjualan.setBackground(new Color(0, 120, 215));
    }//GEN-LAST:event_penjualanMouseExited

    private void penjualanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penjualanMouseEntered
        btn_penjualan.setBackground(new Color(0,0,205));
    }//GEN-LAST:event_penjualanMouseEntered

    private void penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penjualanMouseClicked
        btn_penjualan.setBackground(new Color(0,0,205));
        
        pn_utama.removeAll();
        pn_utama.add(new FormPenjualan());
        pn_utama.repaint();
        pn_utama.revalidate();
       
        
        
    }//GEN-LAST:event_penjualanMouseClicked

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        btn_dashboard.setBackground(new Color(17,107,175));

    }//GEN-LAST:event_dashboardMouseExited

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        btn_dashboard.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        btn_dashboard.setBackground(new Color(0,0,255));

        pn_utama.removeAll();
        pn_utama.add(new FormDashboard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_dashboardMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseExited

    private void btn_logutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logutMouseClicked

    private void btn_logutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logutMouseEntered

    private void btn_logutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_logutMouseExited

    private void pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembelianMouseClicked
        btn_pembelian.setBackground(new Color(0,0,205));
        
        pn_utama.removeAll();
        pn_utama.add(new FormPembelian1());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_pembelianMouseClicked

    private void pembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembelianMouseEntered
        btn_pembelian.setBackground(new Color(0,0,205));
    }//GEN-LAST:event_pembelianMouseEntered

    private void pembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pembelianMouseExited
        btn_pembelian.setBackground(new Color(17,107,175));
    }//GEN-LAST:event_pembelianMouseExited

    private void btn_pembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pembelianMouseClicked

    private void btn_pembelianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pembelianMouseEntered

    private void btn_pembelianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembelianMouseExited
         
    }//GEN-LAST:event_btn_pembelianMouseExited

    private void barang_rusakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barang_rusakMouseClicked
        btn_barang_rusak.setBackground(new Color(0,0,205));
        
        pn_utama.removeAll();
        pn_utama.add(new FormBarangRusak());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_barang_rusakMouseClicked

    private void barang_rusakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barang_rusakMouseEntered
        btn_barang_rusak.setBackground(new Color(0,0,205));
    }//GEN-LAST:event_barang_rusakMouseEntered

    private void barang_rusakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barang_rusakMouseExited
        btn_barang_rusak.setBackground(new Color(17,107,175));
    }//GEN-LAST:event_barang_rusakMouseExited

    private void btn_barang_rusakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barang_rusakMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_barang_rusakMouseClicked

    private void btn_barang_rusakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barang_rusakMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_barang_rusakMouseEntered

    private void btn_barang_rusakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barang_rusakMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_barang_rusakMouseExited

    private void supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseClicked
        btn_supplier.setBackground(new Color(0,0,205));
        
        pn_utama.removeAll();
        pn_utama.add(new FormSupplier());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_supplierMouseClicked

    private void supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseEntered
       btn_supplier.setBackground(new Color(0,0,205));
    }//GEN-LAST:event_supplierMouseEntered

    private void supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseExited
        btn_supplier.setBackground(new Color(17,107,175));
    }//GEN-LAST:event_supplierMouseExited

    private void btn_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplierMouseClicked
        
    }//GEN-LAST:event_btn_supplierMouseClicked

    private void btn_supplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplierMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_supplierMouseEntered

    private void btn_supplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_supplierMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_supplierMouseExited

    private void DashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseClicked
        btn_dashboard.setBackground(new Color(0,0,205));
        
        pn_utama.removeAll();
        pn_utama.add(new FormDashboard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_DashboardMouseClicked

    private void DashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseEntered
        btn_dashboard.setBackground(new Color(0,0,205));
    }//GEN-LAST:event_DashboardMouseEntered

    private void DashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardMouseExited
        btn_dashboard.setBackground(new Color(17,107,175));
    }//GEN-LAST:event_DashboardMouseExited

    private void logo_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo_dashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logo_dashboardMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dashboard;
    private javax.swing.JLabel barang_rusak;
    private javax.swing.JPanel btn_barang_rusak;
    private javax.swing.JPanel btn_dashboard;
    private javax.swing.JPanel btn_inventaris;
    private javax.swing.JPanel btn_karyawan;
    private javax.swing.JPanel btn_laporan;
    private javax.swing.JPanel btn_logut;
    private javax.swing.JPanel btn_pembelian;
    private javax.swing.JPanel btn_penjualan;
    private javax.swing.JPanel btn_supplier;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel inventaris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel karyawan;
    private javax.swing.JLabel laporan_penjualan;
    private javax.swing.JLabel logo_barang_rusak;
    private javax.swing.JLabel logo_dashboard;
    private javax.swing.JLabel logo_inventaris;
    private javax.swing.JLabel logo_karyawan;
    private javax.swing.JLabel logo_laporan;
    private javax.swing.JLabel logo_pembelian;
    private javax.swing.JLabel logo_penjualan;
    private javax.swing.JLabel logo_supplier;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel pembelian;
    private javax.swing.JLabel penjualan;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JLabel supplier;
    // End of variables declaration//GEN-END:variables
}
